FROM golang:1.19.10-alpine AS dev

COPY . /app
WORKDIR /app

# Update
RUN ["apk", "update"]

# Install vim
RUN ["apk", "add", "vim"]

# Add bash_profile
ENV GO111MODULE=on

# Install postgres and rerun
RUN go install github.com/cortesi/modd/cmd/modd@latest

COPY go.mod .
COPY go.sum .

RUN go mod download

CMD ["modd"]

